default_settings: null
behaviors:
  TopScorer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 12000

engine_settings:
  width: 500
  height: 500
  quality_level: 5
  time_scale: 80.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
 
environment_parameters: null
checkpoint_settings:
  run_id: topscorer
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false

